const simpleCheckingProduct = {
  id: '3552ab85-08da-4bb5-be00-9e94d282d310',
  name: 'Simple Checking',
  category: 'CHECKING',
  summary:
    'Simple checking means no fees with online statements and it means no minimum balance required to maintain the account, access to online banking, bill pay and more. You get the benefits you want.',
  content:
    '<p>Simple checking <strong>lorem ipsum</strong> dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>\n<p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\n',
  createdAt: '2020-02-06T12:32:03.341Z',
}

export const bsaRiskResultsMock = [
  {
    position: 1,
    questionId: 'usCitizen',
    answer: 'Yes',
  },
  {
    position: 2,
    questionId: 'countryOfOrigin',
    answer: 'PT',
  },
  {
    position: 3,
    questionId: 'milesAway',
    answer: 'Yes',
  },
  {
    position: 4,
    questionId: 'hearAbout',
    answer: null,
  },
  {
    position: 5,
    questionId: 'incomeIndividual',
    answer: 'No',
  },
  {
    position: 6,
    questionId: 'incomeHouseHold',
    answer: 'Yes',
  },
  {
    position: 7,
    questionId: 'wireTransfersDomestic',
    answer: 'No',
  },
  {
    position: 8,
    questionId: 'wireTransfersInternational',
    answer: 'Yes',
  },
  {
    position: 9,
    questionId: 'cashTransactions',
    answer: 'No',
  },
  {
    position: 10,
    questionId: 'anotherBank',
    answer: 'No',
  },
  {
    position: 11,
    questionId: 'otherBankName',
    answer: 'test',
  },
  {
    position: 12,
    questionId: 'mobileDeposit',
    answer: 'Yes',
  },
  {
    position: 13,
    questionId: 'atmDeposit',
    answer: 'No',
  },
  {
    position: 14,
    questionId: 'directDeposit',
    answer: 'Yes',
  },
]
export const successResponse = {
  id: '2552ab85-08da-4bb5-be00-9e94d282d348',
  status: 'APPROVED',
  statusUpdatedAt: '2019-12-23T15:32:45.397Z',
  statusUpdatedBy: {
    createdAt: '2018-02-16T12:32:03.341Z',
    email: 'demouser@nimblefi.com',
    firstName: 'George',
    id: '1052ab85-08da-4bb5-be00-9e94d282d310',
    lastName: 'Lucas',
  },
  bsa: {
    score: 4,
    risk: 'Low',
  },
  signers: [
    {
      id: '2e31d8c0-1226-4651-8a5d-4bd8aa454722',
      address: 'Some address',
      city: 'Lisbon',
      consent: true,
      dateOfBirth: '2020-03-17',
      invitedAt: '2019-12-23T15:32:45.397Z',
      email: 'test@wearesingular.com',
      firstName: 'Mister',
      lastName: 'U',
      middleName: 'I AM',
      phoneNumber: '222',
      role: 'PRIMARY',
      ssn: '444-222-333',
      state: 'Portugal',
      step: 'DOCUMENT_SENT',
      zipCode: '2033-122',
      employer: 'Singular',
      idProofDocument: {
        type: 'PASSPORT',
        number: '333-222',
        expirationDate: '2020-03-17',
        issuer: 'USA',
        issuedDate: '2020-03-17',
        frontIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
      },
      selfie: {
        default: 'https://wearesingular.com/img/apple-touch-icon.png',
      },
      checkSanction: false,
      sanctionVerifiedAt: '2020-04-01T15:29:24.678Z',
      checkPoliticalExposure: false,
      politicalExposureVerifiedAt: '2020-04-01T15:29:24.678Z',
      checkAdverseMedia: false,
      adverseMediaVerifiedAt: '2020-04-01T15:29:24.678Z',
      checkAntiMoneyLaundering: false,
      antiMoneyLaunderingVerifiedAt: '2020-04-01T15:29:24.678Z',
      status: 'SIGNED',
      contractDocumentSignerStatus: null,
      contractDocumentSignerStatusUpdatedAt: null,
      verificationStatus: {
        faceStatus: 'PENDING',
        faceUpdatedAt: '2018-02-16T12:11:03.341Z',
        documentStatus: 'PENDING',
        documentUpdatedAt: '2018-02-16T12:11:03.341Z',
        addressStatus: 'PENDING',
        addressUpdatedAt: '2018-02-16T12:11:03.341Z',
        sanctionsStatus: 'PENDING',
        sanctionsUpdatedAt: '2018-02-16T12:11:03.341Z',
        mediaStatus: 'MATCH',
        mediaUpdatedAt: '2018-02-16T12:11:03.341Z',
        politicalExposure: 'PENDING',
        politicalExposureUpdatedAt: '2018-02-16T12:11:03.341Z',
      },
      identityVerificationStatus: null,
      identityVerified: true,
      identityVerificationResult: {
        address: {
          partial_address_match_with_id_and_utility_bill: 1,
          full_address: 1,
          address_document_visibility: 1,
          address_document_must_not_be_expired: 1,
          address_document: 1,
          address_document_country: 1,
          selected_type: 1,
        },
        document: {
          issue_date: 1,
          document_visibility: 1,
          document_must_not_be_expired: 1,
          document: 1,
          document_country: 1,
          selected_type: 1,
        },
        face: 1,
      },
    },
    {
      id: 'df3c30f8-fb32-4d1f-9fd9-211637ab1230',
      address: null,
      city: null,
      consent: true,
      dateOfBirth: null,
      invitedAt: '2019-12-23T15:32:46.397Z',
      email: null,
      firstName: null,
      lastName: null,
      middleName: null,
      phoneNumber: null,
      role: 'SECONDARY',
      ssn: null,
      state: null,
      step: 'IMAGES_UPLOADED',
      zipCode: null,
      employer: null,
      idProofDocument: {
        type: null,
        number: null,
        expirationDate: null,
        issuer: null,
        issuedDate: null,
        frontIdProof: {
          default: null,
        },
        backIdProof: {
          default: null,
        }
      },
      selfie: {
        default: null,
      },
      checkSanction: false,
      sanctionVerifiedAt: '2020-04-01T15:29:24.678Z',
      checkPoliticalExposure: false,
      politicalExposureVerifiedAt: '2020-04-01T15:29:24.678Z',
      checkAdverseMedia: false,
      adverseMediaVerifiedAt: '2020-04-01T15:29:24.678Z',
      checkAntiMoneyLaundering: false,
      antiMoneyLaunderingVerifiedAt: '2020-04-01T15:29:24.678Z',
      status: 'PENDING',
      contractDocumentSignerStatus: null,
      contractDocumentSignerStatusUpdatedAt: null,
      verificationStatus: {
        faceStatus: 'VALID',
        faceUpdatedAt: '2018-03-16T11:32:03.341Z',
        documentStatus: 'INVALID',
        documentUpdatedAt: '2018-03-16T11:32:03.341Z',
        addressStatus: 'PENDING',
        addressUpdatedAt: '2018-03-16T11:32:03.341Z',
        sanctionsStatus: 'NOMATCH',
        sanctionsUpdatedAt: '2018-03-16T11:32:03.341Z',
        mediaStatus: 'NOMATCH',
        mediaUpdatedAt: '2018-03-16T11:32:03.341Z',
        politicalExposure: 'MATCH',
        politicalExposureUpdatedAt: '2018-03-16T11:32:03.341Z',
      },
      identityVerificationResult: null,
      identityVerificationStatus: null,
      identityVerified: null
    },
    {
      id: 'df3c30f8-fb32-4d1f-9fd9-211637ab1230',
      address: null,
      city: null,
      consent: true,
      dateOfBirth: null,
      email: null,
      firstName: null,
      lastName: null,
      middleName: null,
      phoneNumber: null,
      role: 'SECONDARY',
      ssn: null,
      state: null,
      step: 'IMAGES_UPLOADED',
      zipCode: null,
      idProofDocument: {
        type: null,
        number: null,
        expirationDate: null,
        issuer: null,
        issuedDate: null,
        frontIdProof: {
          default: null,
        },
        backIdProof: {
          default: null,
        }
      },
      selfie: {
        default: null,
      },
      status: 'INVITED',
      contractDocumentSignerStatus: null,
      contractDocumentSignerStatusUpdatedAt: null,
      verificationStatus: {
        faceStatus: 'VALID',
        faceUpdatedAt: '2018-03-16T11:32:03.341Z',
        documentStatus: 'VALID',
        documentUpdatedAt: '2018-03-16T11:32:03.341Z',
        addressStatus: 'VALID',
        addressUpdatedAt: '2018-03-16T11:32:03.341Z',
        sanctionsStatus: 'NOMATCH',
        sanctionsUpdatedAt: '2018-03-16T11:32:03.341Z',
        mediaStatus: 'NOMATCH',
        mediaUpdatedAt: '2018-03-16T11:32:03.341Z',
        politicalExposure: 'NOMATCH',
        politicalExposureUpdatedAt: '2018-03-16T11:32:03.341Z',
      },
      identityVerificationResult: null,
      identityVerificationStatus: null,
      identityVerified: null,
    },
    {
      id: '2e31d8c0-1226-4651-8a5d-4bd8aa454722',
      address: 'Some address',
      city: 'Lisbon',
      consent: true,
      dateOfBirth: '2020-03-17',
      email: 'test@wearesingular.com',
      firstName: 'Mister',
      lastName: 'U',
      middleName: 'I AM',
      phoneNumber: '222',
      role: 'PRIMARY',
      ssn: '444-222-333',
      state: 'Portugal',
      step: 'DOCUMENT_SENT',
      zipCode: '2033-122',
      idProofDocument: {
        type: 'USDL',
        number: '333-222',
        expirationDate: '2020-03-17',
        issuer: 'CA',
        issuedDate: '2020-03-17',
        frontIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        backIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
      },
      selfie: {
        default: 'https://wearesingular.com/img/apple-touch-icon.png',
      },
      checkSanction: null,
      sanctionVerifiedAt: null,
      checkPoliticalExposure: null,
      politicalExposureVerifiedAt: null,
      checkAdverseMedia: null,
      adverseMediaVerifiedAt: null,
      checkAntiMoneyLaundering: null,
      antiMoneyLaunderingVerifiedAt: null,
      status: 'INVITED',
      contractDocumentSignerStatus: null,
      contractDocumentSignerStatusUpdatedAt: null,
      verificationStatus: {
        faceStatus: 'NOMATCH',
        faceUpdatedAt: '2018-03-16T11:32:03.341Z',
        documentStatus: 'VALID',
        documentUpdatedAt: '2018-03-16T11:32:03.341Z',
        addressStatus: 'VALID',
        addressUpdatedAt: '2018-03-16T11:32:03.341Z',
        sanctionsStatus: 'NOMATCH',
        sanctionsUpdatedAt: '2018-03-16T11:32:03.341Z',
        mediaStatus: 'VALID',
        mediaUpdatedAt: '2018-03-16T11:32:03.341Z',
        politicalExposure: 'VALID',
        politicalExposureUpdatedAt: '2018-03-16T11:32:03.341Z',
      },
      identityVerificationStatus: null,
      identityVerified: true,
      identityVerificationResult: {
        address: {
          partial_address_match_with_id_and_utility_bill: 1,
          full_address: 1,
          address_document_visibility: 1,
          address_document_must_not_be_expired: 1,
          address_document: 1,
          address_document_country: 1,
          selected_type: 1,
        },
        document: {
          issue_date: 1,
          document_visibility: 1,
          document_must_not_be_expired: 1,
          document: 1,
          document_country: 1,
          selected_type: 1,
        },
        face: 1,
      },
    },
  ],
  createdAt: '2019-03-16T12:34:11.341Z',
  contractDocumentEnvelopeStatus: 'CREATED',
  contractDocumentCreatedAt: '2019-03-16T12:34:11.341Z',
  contractDocumentEnvelopeStatusUpdatedAt: '2019-03-16T12:34:11.341Z',
  contract: {
    uri: 'https://google.com',
  },
  productConfigurations: [
    {
      productId: '3552ab85-08da-4bb5-be00-9e94d282d310',
      createdAt: '2019-03-16T12:34:11.341Z',
      product: simpleCheckingProduct,
      initialDeposit: 3000,
    },
  ],
  verificationStatus: {
    faceStatus: 'VALID',
    documentStatus: 'INVALID',
    addressStatus: 'INVALID',
    sanctionsStatus: 'NOMATCH',
    mediaStatus: 'NOMATCH',
    politicalExposure: 'MATCH',
  },
}
export const successResponseApproved = {
  id: '2552ab85-08da-4bb5-be00-9e94d282d348',
  status: 'APPROVED',
  statusUpdatedAt: '2019-12-23T15:32:45.397Z',
  statusUpdatedBy: {
    createdAt: '2018-02-16T12:32:03.341Z',
    email: 'demouser@nimblefi.com',
    firstName: 'George',
    id: '1052ab85-08da-4bb5-be00-9e94d282d310',
    lastName: 'Lucas',
  },
  bsa: {
    score: 4,
    risk: 'Low',
  },
  signers: [
    {
      role: 'PRIMARY',
      id: 'daad600a-1c36-45c4-b61d-b2ae7186a24c',
      status: 'SIGNED',
      firstName: 'Han',
      middleName: 'James',
      lastName: 'Solo',
      address: '2405 148TH CT',
      city: 'Urbandale',
      state: 'IA',
      zipCode: '50353',
      phoneNumber: '(345) 654-3543',
      ssn: '367-65-4567',
      email: 'han@james.solo',
      employer: 'Resistance',
      dateOfBirth: '1988-01-28T00:00:00.000Z',
      emailVerified: false,
      emailVerifiedAt: null,
      consent: true,
      checkSanction: null,
      sanctionVerifiedAt: null,
      checkPoliticalExposure: null,
      politicalExposureVerifiedAt: null,
      checkAdverseMedia: null,
      adverseMediaVerifiedAt: null,
      checkAntiMoneyLaundering: null,
      antiMoneyLaunderingVerifiedAt: null,
      contractDocumentSignerStatus: 'COMPLETED',
      contractDocumentSignerStatusUpdatedAt: '2021-02-19T00:01:21.729Z',
      invitedAt: '2021-02-19T00:00:22.908Z',
      idProofDocument: {
        backIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        expirationDate: '2222-12-05',
        frontIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        issuedDate: '1970-01-01',
        issuer: 'USA',
        number: '910239248',
        type: 'PASSPORT',
      },
      selfie: {
        default: 'https://wearesingular.com/img/apple-touch-icon.png',
      },
      verificationStatus: {
        faceStatus: 'INVALID',
        faceUpdatedAt: '2021-02-19T00:06:31.299Z',
        documentStatus: 'INVALID',
        documentUpdatedAt: '2021-02-19T00:06:31.299Z',
        addressStatus: 'INVALID',
        addressUpdatedAt: '2021-02-19T00:06:31.299Z',
        sanctionsStatus: 'NOMATCH',
        sanctionsUpdatedAt: '2021-02-19T00:00:54.271Z',
        mediaStatus: 'NOMATCH',
        mediaUpdatedAt: '2021-02-19T00:00:54.276Z',
        politicalExposure: 'NOMATCH',
        politicalExposureUpdatedAt: '2021-02-19T00:00:54.280Z',
      },
    },
    {
      role: 'SECONDARY',
      id: '6d731f27-2c6e-4ba1-bb1c-061a55b2e1cf',
      status: 'SIGNED',
      firstName: 'Mark',
      middleName: 'James',
      lastName: 'Brown',
      address: '2405 148TH CT',
      city: 'Urbandale',
      state: 'IA',
      zipCode: '50353',
      phoneNumber: '(876) 543-4654',
      ssn: '456-54-3565',
      email: 'formadora@gmail.com',
      employer: 'QQQ',
      dateOfBirth: '1988-01-28T00:00:00.000Z',
      emailVerified: false,
      emailVerifiedAt: null,
      consent: true,
      checkSanction: null,
      sanctionVerifiedAt: null,
      checkPoliticalExposure: null,
      politicalExposureVerifiedAt: null,
      checkAdverseMedia: null,
      adverseMediaVerifiedAt: null,
      checkAntiMoneyLaundering: null,
      antiMoneyLaunderingVerifiedAt: null,
      contractDocumentSignerStatus: 'COMPLETED',
      contractDocumentSignerStatusUpdatedAt: '2021-02-19T00:02:57.893Z',
      invitedAt: '2021-02-19T00:00:23.952Z',
      idProofDocument: {
        backIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        expirationDate: '2222-12-05',
        frontIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        issuedDate: '1970-01-01',
        issuer: 'USA',
        number: '910239248',
        type: 'PASSPORT',
      },
      selfie: {
        default: 'https://wearesingular.com/img/apple-touch-icon.png',
      },
      verificationStatus: {
        faceStatus: 'INVALID',
        faceUpdatedAt: '2021-02-19T00:06:03.894Z',
        documentStatus: 'INVALID',
        documentUpdatedAt: '2021-02-19T00:06:03.894Z',
        addressStatus: 'INVALID',
        addressUpdatedAt: '2021-02-19T00:06:03.894Z',
        sanctionsStatus: 'NOMATCH',
        sanctionsUpdatedAt: '2021-02-19T00:03:08.972Z',
        mediaStatus: 'NOMATCH',
        mediaUpdatedAt: '2021-02-19T00:03:08.976Z',
        politicalExposure: 'NOMATCH',
        politicalExposureUpdatedAt: '2021-02-19T00:03:08.980Z',
      },
    },
  ],
  createdAt: '2019-03-16T12:34:11.341Z',
  contractDocumentEnvelopeStatus: 'CREATED',
  contractDocumentCreatedAt: '2019-03-16T12:34:11.341Z',
  contractDocumentEnvelopeStatusUpdatedAt: '2019-03-16T12:34:11.341Z',
  contract: {
    uri: 'https://google.com',
  },
  productConfigurations: [
    {
      productId: '1a8b1d5b-5601-4706-95ad-6f92f376752e',
      initialDeposit: 0,
      createdAt: '2021-02-22T12:13:57.601Z',
      product: {
        id: '1a8b1d5b-5601-4706-95ad-6f92f376752e',
        name: 'Simple Checking',
        category: 'CHECKING',
        sku: 'simple-checking',
        summary:
          'Simple Checking means no fees with online statements. And, it means no minimum balance required to maintain the account, access to online banking, bill pay and more. You get the benefits you want.',
        content:
          '<p><strong>Simple Checking</strong> offers numerous benefits for account holders, including:</p>\n<ul>\n<li>$100 minimum deposit to open account</li>\n<li>No minimum balance required</li>\n<li>Free Shazam®Chek Card* with No ATM Fees**</li>\n<li>Free Online Banking</li>\n<li>Free Online Bill Pay</li>\n<li>Bankline 24/7</li>\n<li>Free Mobile Banking***</li>\n<li>Free Mobile Deposit*</li>\n<li>Direct Deposit</li>\n<li>Free online statements or $3/statement mailed</li>\n<li>Overdraft Reserve on qualifying accounts*</li>\n<li>First order basic wallet checks free</li>\n</ul>\n<p>*Shazam®Chek Card, Mobile Deposit, Overdraft Reserve and Credit Cards are subject to approval.</p>\n<p>**If you receive an ATM surcharge, bring in or mail your original ATM receipt within 60 days and we will refund the surcharge. Excludes foreign surcharge fees. </p>\n<p>***Although Central Bank does not charge for Mobile Banking, standard text messaging and data plan fees from your mobile phone carrier may apply. Please consult your carrier before using Mobile Banking.</p>\n<p>Service charge subject to Iowa &amp; Local Option sales tax, excluding our South Dakota locations.</p>\n',
        createdAt: '2020-10-07T17:50:09.510Z',
        options: [
          {
            id: null,
            key: 'account_number',
            category: 'account_number',
            title: 'Account Number',
            value: 'TEST710000320',
            lead: null,
            annotation: null,
            parentId: null,
          },
          {
            id: 'b81ae119-46eb-49eb-9c9f-3e5a98ac4cd9',
            key: 'bill_pay',
            category: 'product_feature',
            title: 'Bill Pay',
            value: 'true',
            lead: null,
            annotation: 'Free',
            parentId: '02777e58-4f03-4a54-bc70-add9f27e9629',
          },
          {
            id: '53005bad-ec77-4e33-80ed-deb25b0c3c49',
            key: 'debit_card',
            category: 'product_feature',
            title: 'Debit Card',
            value: 'true',
            lead: 'Shazam®Chek Card',
            annotation: 'Free',
            parentId: null,
          },
          {
            id: 'cef38015-f0e3-46e6-b1ca-3fd1af0650ad',
            key: 'e_statements',
            category: 'product_feature',
            title: 'E-Statements',
            value: 'true',
            lead: 'Get your bank statements directly on your email',
            annotation: 'Free',
            parentId: null,
          },
          {
            id: '02777e58-4f03-4a54-bc70-add9f27e9629',
            key: 'mobile_and_online_banking',
            category: 'product_feature',
            title: 'Mobile & Online Banking',
            value: 'true',
            lead: null,
            annotation: 'Free',
            parentId: null,
          },
          {
            id: '25388dd9-4741-4213-ba1a-d2ed46b54c68',
            key: 'mobile_deposits',
            category: 'product_feature',
            title: 'Mobile Deposits',
            value: 'true',
            lead: null,
            annotation: 'Free',
            parentId: '02777e58-4f03-4a54-bc70-add9f27e9629',
          },
          {
            id: '2c5b79a0-e7af-4bfd-afe3-50f251910356',
            key: 'paper_statements',
            category: 'product_feature',
            title: 'Paper Statements',
            value: 'false',
            lead: null,
            annotation: '$3/statement',
            parentId: null,
          },
        ],
      },
    },
  ],
  verificationStatus: {
    faceStatus: 'VALID',
    documentStatus: 'INVALID',
    addressStatus: 'INVALID',
    sanctionsStatus: 'NOMATCH',
    mediaStatus: 'NOMATCH',
    politicalExposure: 'MATCH',
  },
}
export const successResponsePending = {
  id: '86342423dcf685-f1d6-46ed-810f-96dc298f74e1',
  status: 'INCOMPLETE',
  signers: [
    {
      role: 'PRIMARY',
      id: '743c8927-330a-43e7-b851-d5e3c9a185a2',
      status: 'PENDING',
      firstName: 'Captain',
      middleName: 'James',
      lastName: 'Kirk',
      address: 'Enterprise',
      city: 'Universe',
      state: 'NY',
      zipCode: '10000',
      phoneNumber: '(202) 222-2222',
      ssn: '123-45-3222',
      email: 'kirk_james@enterprise.un',
      employer: 'Fleet',
      dateOfBirth: '1977-01-01T00:00:00.000Z',
      emailVerified: true,
      emailVerifiedAt: '2222-01-01T00:00:00.000Z',
      consent: true,
      idProofDocument: {
        backIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        expirationDate: '2222-12-05',
        frontIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        issuedDate: '1970-01-01',
        issuer: 'USA',
        number: '910239248',
        type: 'PASSPORT',
      },
      checkSanction: null,
      sanctionVerifiedAt: null,
      checkPoliticalExposure: null,
      politicalExposureVerifiedAt: null,
      checkAdverseMedia: null,
      adverseMediaVerifiedAt: null,
      checkAntiMoneyLaundering: null,
      antiMoneyLaunderingVerifiedAt: null,
      contractDocumentSignerStatus: 'SENT',
      contractDocumentSignerStatusUpdatedAt: '2021-02-19T14:48:37.709Z',
      invitedAt: '2021-02-19T14:48:07.734Z',
      selfie: {
        default:
          'https://api.dev.nimblefi.com/v1/documents/8311f8a3-1a04-4925-a1d5-ecc9bc66412f?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOm51bGwsInNjb3BlcyI6WyJkb2N1bWVudHMiXSwicmVzb3VyY2VzIjpbImRvY3VtZW50cyM4MzExZjhhMy0xYTA0LTQ5MjUtYTFkNS1lY2M5YmM2NjQxMmYiXSwiaXNzIjoiaHR0cHM6Ly9hcGkuZGV2Lm5pbWJsZWZpLmNvbSIsInN1YiI6Imh0dHBzOi8vYXBpLmRldi5uaW1ibGVmaS5jb20vdjEvdXNlcnMvbnVsbCIsImF1ZCI6Imh0dHBzOi8vYXBpLmRldi5uaW1ibGVmaS5jb20iLCJleHAiOjE2MTQwMDgxNDMsImlhdCI6MTYxNDAwNzI0M30.sYsEwL9qDK4Hz6TZn8hAu6CgubiXgH-iuftLZNN8e7FN2qEZJLGLs0nlHoc4JitCmbrLiN9wsBs3MIOTNbsxIw',
      },
      verificationStatus: {
        faceStatus: 'INVALID',
        faceUpdatedAt: '2021-02-19T14:49:37.177Z',
        documentStatus: 'INVALID',
        documentUpdatedAt: '2021-02-19T14:49:37.178Z',
        addressStatus: 'INVALID',
        addressUpdatedAt: '2021-02-19T14:49:37.178Z',
        sanctionsStatus: 'NOMATCH',
        sanctionsUpdatedAt: '2021-02-19T14:48:39.360Z',
        mediaStatus: 'NOMATCH',
        mediaUpdatedAt: '2021-02-19T14:48:39.365Z',
        politicalExposure: 'NOMATCH',
        politicalExposureUpdatedAt: '2021-02-19T14:48:39.369Z',
      },
    },
    {
      role: 'SECONDARY',
      id: 'c5e575e0-88ae-4f14-8f0e-63a93dfe21b0',
      status: 'INVITED',
      firstName: null,
      middleName: null,
      lastName: null,
      address: null,
      city: null,
      state: null,
      zipCode: null,
      phoneNumber: null,
      ssn: null,
      email: 'data@enterprise.com',
      employer: null,
      dateOfBirth: null,
      emailVerified: false,
      emailVerifiedAt: null,
      consent: false,
      checkSanction: null,
      sanctionVerifiedAt: null,
      checkPoliticalExposure: null,
      politicalExposureVerifiedAt: null,
      checkAdverseMedia: null,
      adverseMediaVerifiedAt: null,
      checkAntiMoneyLaundering: null,
      antiMoneyLaunderingVerifiedAt: null,
      contractDocumentSignerStatus: 'CREATED',
      contractDocumentSignerStatusUpdatedAt: '2021-02-19T14:48:37.714Z',
      invitedAt: '2021-02-22T14:29:54.194Z',
      idProofDocument: {
        backIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        expirationDate: '2222-12-05',
        frontIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        issuedDate: '1970-01-01',
        issuer: 'USA',
        number: '910239248',
        type: 'PASSPORT',
      },
      selfie: {
        default: null,
      },
      verificationStatus: {
        faceStatus: 'PENDING',
        faceUpdatedAt: '2021-02-19T14:48:07.734Z',
        documentStatus: 'PENDING',
        documentUpdatedAt: '2021-02-19T14:48:07.734Z',
        addressStatus: 'PENDING',
        addressUpdatedAt: '2021-02-19T14:48:07.734Z',
        sanctionsStatus: 'PENDING',
        sanctionsUpdatedAt: '2021-02-19T14:48:07.734Z',
        mediaStatus: 'PENDING',
        mediaUpdatedAt: '2021-02-19T14:48:07.734Z',
        politicalExposure: 'PENDING',
        politicalExposureUpdatedAt: '2021-02-19T14:48:07.734Z',
      },
    },
  ],
  createdAt: '2021-02-19T14:48:07.746Z',
  statusUpdatedBy: null,
  statusUpdatedAt: null,
  statusEmailSubject: null,
  statusEmailBody: null,
  contractDocumentCreatedAt: '2021-02-19T14:48:16.741Z',
  contractDocumentEnvelopeStatus: 'SENT',
  contractDocumentEnvelopeStatusUpdatedAt: '2021-02-19T14:48:37.705Z',
  productConfigurations: [
    {
      productId: 'a4f6f570-3888-49bc-b2e3-c243d6e152eb',
      initialDeposit: 0,
      createdAt: '2021-02-19T14:48:08.308Z',
      product: {
        id: 'a4f6f570-3888-49bc-b2e3-c243d6e152eb',
        name: 'Platinum Checking',
        category: 'CHECKING',
        sku: 'platinum-checking',
        summary:
          'With variable interest paid at tiered rates - the higher your balance, the better your rates – Platinum Checking is perfect for when you want to have cash available and make that balance work for you. Platinum Checking rewards your relationship and is free for Emerald Club members and customers who have their first mortgage with us.',
        content:
          '<p><strong>Shamrock Checking</strong> offers more than just interest to account holders. It also provides the same benefits as our other CHECKING accounts combined with free cashier&#39;s checks and money orders:</p>\n<ul>\n<li>Free Shazam®Chek Card* with No ATM Fees**</li>\n<li>Free Online Banking</li>\n<li>Free Online Bill Pay</li>\n<li>Bankline 24/7</li>\n<li>Free Mobile Banking***</li>\n<li>Free Mobile Deposit*</li>\n<li>Free online statements or free monthly statements mailed</li>\n<li>Overdraft Reserve on qualifying accounts*</li>\n<li>Free basic wallet checks, limit 1 box/order</li>\n<li>Free Cashier&#39;s Check/Money Orders – limit 3/month</li>\n</ul>\n<p><strong>Variable interest, paid monthly based on the following balance tiers:</strong></p>\n<ul>\n<li>$50,000.00 and above</li>\n<li>$25,000.00 – $49,999.99</li>\n<li>$10,000.00 – $24,999.99</li>\n<li>Up to $9,999.99</li>\n</ul>\n<p><strong>Additional Information About Platinum Checking</strong></p>\n<ul>\n<li>$100 minimum to open account</li>\n<li>$15,000 minimum consumer relationship, includes deposits and loans, to avoid fees</li>\n<li>If below relationship qualifications, $9.99/statement cycle service charge</li>\n<li>Closed-end consumer loan rate reduction of 0.25% on any new loan.****</li>\n<li>$150 off mortgage origination fees</li>\n<li>0.10% bonus rate on new CDs*****</li>\n<li>Platinum Checking is free for Emerald Club members and customers who have their first mortgage with us</li>\n</ul>\n<p>*Shazam®Chek Card, Mobile Deposit, Overdraft Reserve and Credit Cards are subject to approval.</p>\n<p>**If you receive an ATM surcharge, bring in or mail your original ATM receipt within 60 days and we will refund the surcharge. Excludes foreign surcharge fees. </p>\n<p>***Although Central Bank does not charge for Mobile Banking, standard text messaging and data plan fees from your mobile phone carrier may apply. Please consult your carrier before using Mobile Banking.</p>\n<p>****Rate reduction is not valid with any other promotional offers.</p>\n<p>*****Bonus rate on new CDs is not valid on CD Plus, Rule Breaker CDs or with any other promotional offers.</p>\n<p>Service charge subject to Iowa &amp; Local Option sales tax, excluding our South Dakota locations.</p>\n',
        createdAt: '2020-10-07T17:51:35.602Z',
        options: [
          {
            id: null,
            key: 'account_number',
            category: 'account_number',
            title: 'Account Number',
            value: 'TEST710000319',
            lead: null,
            annotation: null,
            parentId: null,
          },
          {
            id: '726d5b1f-e096-4491-9f97-05b827130a79',
            key: 'bill_pay',
            category: 'product_feature',
            title: 'Bill Pay',
            value: 'true',
            lead: null,
            annotation: 'Free',
            parentId: 'c4ea13be-7f75-4c27-b748-b5a449e1b56d',
          },
          {
            id: 'ac788c04-3c8a-4f0e-8d2d-4011e6f35a48',
            key: 'debit_card',
            category: 'product_feature',
            title: 'Debit Card',
            value: 'true',
            lead: 'Shazam®Chek Card',
            annotation: 'Free',
            parentId: null,
          },
          {
            id: '82be19ca-2e86-4fe4-a485-0d9eea84fdf8',
            key: 'e_statements',
            category: 'product_feature',
            title: 'E-Statements',
            value: 'true',
            lead: 'Get your bank statements directly on your email',
            annotation: 'Free',
            parentId: null,
          },
          {
            id: 'c4ea13be-7f75-4c27-b748-b5a449e1b56d',
            key: 'mobile_and_online_banking',
            category: 'product_feature',
            title: 'Mobile & Online Banking',
            value: 'true',
            lead: null,
            annotation: 'Free',
            parentId: null,
          },
          {
            id: '796e762a-29af-4ca1-87bf-02eda98aef3a',
            key: 'mobile_deposits',
            category: 'product_feature',
            title: 'Mobile Deposits',
            value: 'true',
            lead: null,
            annotation: 'Free',
            parentId: 'c4ea13be-7f75-4c27-b748-b5a449e1b56d',
          },
          {
            id: '281ec6af-fef4-44a0-aa86-64c2d21686b7',
            key: 'paper_statements',
            category: 'product_feature',
            title: 'Paper Statements',
            value: 'false',
            lead: null,
            annotation: '$3/statement',
            parentId: null,
          },
        ],
      },
    },
  ],
  contract: {
    uri:
      'https://api.dev.nimblefi.com/v1/documents/49089e93-069f-4f7b-948f-3ba044784c56?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOm51bGwsInNjb3BlcyI6WyJkb2N1bWVudHMiXSwicmVzb3VyY2VzIjpbImRvY3VtZW50cyM0OTA4OWU5My0wNjlmLTRmN2ItOTQ4Zi0zYmEwNDQ3ODRjNTYiXSwiaXNzIjoiaHR0cHM6Ly9hcGkuZGV2Lm5pbWJsZWZpLmNvbSIsInN1YiI6Imh0dHBzOi8vYXBpLmRldi5uaW1ibGVmaS5jb20vdjEvdXNlcnMvbnVsbCIsImF1ZCI6Imh0dHBzOi8vYXBpLmRldi5uaW1ibGVmaS5jb20iLCJleHAiOjE2MTQwMDgxNDMsImlhdCI6MTYxNDAwNzI0M30.om77XGsTzpd3050SQyCW1S-9PHammJnutHotaS74rHX9kITYz2bQBYd2hS5lFffOcXZSS5IwACQQHpxfYD183Q',
  },
  verificationStatus: {
    faceStatus: 'PENDING',
    documentStatus: 'PENDING',
    addressStatus: 'PENDING',
    sanctionsStatus: 'PENDING',
    mediaStatus: 'PENDING',
    politicalExposure: 'PENDING',
  },
  bsa: {
    risk: 'High',
    score: 8,
  },
}
export const successResponseMultiple = [
  successResponseApproved,
  successResponsePending,
]
export const successResponseDeclined = {
  id: '2552ab85-08da-4bb5-be00-9e94d282d348',
  status: 'DECLINED',
  statusUpdatedAt: '2019-12-23T15:32:45.397Z',
  statusUpdatedBy: {
    createdAt: '2018-02-16T12:32:03.341Z',
    email: 'demouser@nimblefi.com',
    firstName: 'George',
    id: '1052ab85-08da-4bb5-be00-9e94d282d310',
    lastName: 'Lucas',
  },
  bsa: {
    score: 4,
    risk: 'Low',
  },
  signers: [
    {
      id: '2e31d8c0-1226-4651-8a5d-4bd8aa454722',
      address: 'Some address',
      city: 'Lisbon',
      consent: true,
      dateOfBirth: '2020-03-17',
      invitedAt: '2019-12-23T15:32:45.397Z',
      email: 'test@wearesingular.com',
      firstName: 'Mister',
      identityVerificationStatus: null,
      identityVerified: true,
      identityVerificationResult: {
        address: {
          partial_address_match_with_id_and_utility_bill: 1,
          full_address: 1,
          address_document_visibility: 1,
          address_document_must_not_be_expired: 1,
          address_document: 1,
          address_document_country: 1,
          selected_type: 1,
        },
        document: {
          issue_date: 1,
          document_visibility: 1,
          document_must_not_be_expired: 1,
          document: 1,
          document_country: 1,
          selected_type: 1,
        },
        face: 1,
      },
      lastName: 'U',
      middleName: 'I AM',
      phoneNumber: '222',
      role: 'PRIMARY',
      ssn: '444-222-333',
      state: 'Portugal',
      step: 'DOCUMENT_SENT',
      zipCode: '2033-122',
      employer: 'Singular',
      idProofDocument: {
        backIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        expirationDate: '2222-12-05',
        frontIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        issuedDate: '1970-01-01',
        issuer: 'USA',
        number: '910239248',
        type: 'PASSPORT',
      },
      selfie: {
        default: 'https://wearesingular.com/img/apple-touch-icon.png',
      },
      checkSanction: false,
      sanctionVerifiedAt: '2020-04-01T15:29:24.678Z',
      checkPoliticalExposure: false,
      politicalExposureVerifiedAt: '2020-04-01T15:29:24.678Z',
      checkAdverseMedia: false,
      adverseMediaVerifiedAt: '2020-04-01T15:29:24.678Z',
      checkAntiMoneyLaundering: false,
      antiMoneyLaunderingVerifiedAt: '2020-04-01T15:29:24.678Z',
      status: 'SIGNED',
      contractDocumentSignerStatus: null,
      contractDocumentSignerStatusUpdatedAt: null,
      verificationStatus: {
        faceStatus: 'PENDING',
        faceUpdatedAt: '2018-02-16T12:11:03.341Z',
        documentStatus: 'PENDING',
        documentUpdatedAt: '2018-02-16T12:11:03.341Z',
        addressStatus: 'PENDING',
        addressUpdatedAt: '2018-02-16T12:11:03.341Z',
        sanctionsStatus: 'PENDING',
        sanctionsUpdatedAt: '2018-02-16T12:11:03.341Z',
        mediaStatus: 'MATCH',
        mediaUpdatedAt: '2018-02-16T12:11:03.341Z',
        politicalExposure: 'PENDING',
        politicalExposureUpdatedAt: '2018-02-16T12:11:03.341Z',
      },
    },
    {
      id: 'df3c30f8-fb32-4d1f-9fd9-211637ab1230',
      address: null,
      city: null,
      consent: true,
      dateOfBirth: null,
      invitedAt: '2019-12-23T15:32:46.397Z',
      email: null,
      firstName: null,
      identityVerificationResult: null,
      identityVerificationStatus: null,
      identityVerified: null,
      lastName: null,
      middleName: null,
      phoneNumber: null,
      role: 'SECONDARY',
      ssn: null,
      state: null,
      step: 'IMAGES_UPLOADED',
      zipCode: null,
      idProofDocument: {
        backIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        expirationDate: '2222-12-05',
        frontIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        issuedDate: '1970-01-01',
        issuer: 'USA',
        number: '910239248',
        type: 'PASSPORT',
      },
      selfie: {
        default: 'https://wearesingular.com/img/apple-touch-icon.png',
      },
      checkSanction: false,
      sanctionVerifiedAt: '2020-04-01T15:29:24.678Z',
      checkPoliticalExposure: false,
      politicalExposureVerifiedAt: '2020-04-01T15:29:24.678Z',
      checkAdverseMedia: false,
      adverseMediaVerifiedAt: '2020-04-01T15:29:24.678Z',
      checkAntiMoneyLaundering: false,
      antiMoneyLaunderingVerifiedAt: '2020-04-01T15:29:24.678Z',
      status: 'PENDING',
      contractDocumentSignerStatus: null,
      contractDocumentSignerStatusUpdatedAt: null,
      verificationStatus: {
        faceStatus: 'VALID',
        faceUpdatedAt: '2018-03-16T11:32:03.341Z',
        documentStatus: 'INVALID',
        documentUpdatedAt: '2018-03-16T11:32:03.341Z',
        addressStatus: 'PENDING',
        addressUpdatedAt: '2018-03-16T11:32:03.341Z',
        sanctionsStatus: 'NOMATCH',
        sanctionsUpdatedAt: '2018-03-16T11:32:03.341Z',
        mediaStatus: 'NOMATCH',
        mediaUpdatedAt: '2018-03-16T11:32:03.341Z',
        politicalExposure: 'MATCH',
        politicalExposureUpdatedAt: '2018-03-16T11:32:03.341Z',
      },
    },
    {
      id: 'df3c30f8-fb32-4d1f-9fd9-211637ab1230',
      address: null,
      city: null,
      consent: true,
      dateOfBirth: null,
      email: null,
      firstName: null,
      identityVerificationResult: null,
      identityVerificationStatus: null,
      identityVerified: null,
      lastName: null,
      middleName: null,
      phoneNumber: null,
      role: 'SECONDARY',
      ssn: null,
      state: null,
      step: 'IMAGES_UPLOADED',
      zipCode: null,
      idProofDocument: {
        backIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        expirationDate: '2222-12-05',
        frontIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        issuedDate: '1970-01-01',
        issuer: 'USA',
        number: '910239248',
        type: 'PASSPORT',
      },
      selfie: {
        default: 'https://wearesingular.com/img/apple-touch-icon.png',
      },
      status: 'INVITED',
      contractDocumentSignerStatus: null,
      contractDocumentSignerStatusUpdatedAt: null,
      verificationStatus: {
        faceStatus: 'VALID',
        faceUpdatedAt: '2018-03-16T11:32:03.341Z',
        documentStatus: 'VALID',
        documentUpdatedAt: '2018-03-16T11:32:03.341Z',
        addressStatus: 'VALID',
        addressUpdatedAt: '2018-03-16T11:32:03.341Z',
        sanctionsStatus: 'NOMATCH',
        sanctionsUpdatedAt: '2018-03-16T11:32:03.341Z',
        mediaStatus: 'NOMATCH',
        mediaUpdatedAt: '2018-03-16T11:32:03.341Z',
        politicalExposure: 'NOMATCH',
        politicalExposureUpdatedAt: '2018-03-16T11:32:03.341Z',
      },
    },
    {
      id: '2e31d8c0-1226-4651-8a5d-4bd8aa454722',
      address: 'Some address',
      city: 'Lisbon',
      consent: true,
      dateOfBirth: '2020-03-17',
      email: 'test@wearesingular.com',
      firstName: 'Mister',
      identityVerificationStatus: null,
      identityVerified: true,
      identityVerificationResult: {
        address: {
          partial_address_match_with_id_and_utility_bill: 1,
          full_address: 1,
          address_document_visibility: 1,
          address_document_must_not_be_expired: 1,
          address_document: 1,
          address_document_country: 1,
          selected_type: 1,
        },
        document: {
          issue_date: 1,
          document_visibility: 1,
          document_must_not_be_expired: 1,
          document: 1,
          document_country: 1,
          selected_type: 1,
        },
        face: 1,
      },
      lastName: 'U',
      middleName: 'I AM',
      phoneNumber: '222',
      role: 'PRIMARY',
      ssn: '444-222-333',
      state: 'Portugal',
      step: 'DOCUMENT_SENT',
      zipCode: '2033-122',
      idProofDocument: {
        backIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        expirationDate: '2222-12-05',
        frontIdProof: {
          default: 'https://wearesingular.com/img/apple-touch-icon.png',
        },
        issuedDate: '1970-01-01',
        issuer: 'USA',
        number: '910239248',
        type: 'PASSPORT',
      },
      selfie: {
        default: 'https://wearesingular.com/img/apple-touch-icon.png',
      },
      checkSanction: null,
      sanctionVerifiedAt: null,
      checkPoliticalExposure: null,
      politicalExposureVerifiedAt: null,
      checkAdverseMedia: null,
      adverseMediaVerifiedAt: null,
      checkAntiMoneyLaundering: null,
      antiMoneyLaunderingVerifiedAt: null,
      status: 'INVITED',
      contractDocumentSignerStatus: null,
      contractDocumentSignerStatusUpdatedAt: null,
      verificationStatus: {
        faceStatus: 'NOMATCH',
        faceUpdatedAt: '2018-03-16T11:32:03.341Z',
        documentStatus: 'VALID',
        documentUpdatedAt: '2018-03-16T11:32:03.341Z',
        addressStatus: 'VALID',
        addressUpdatedAt: '2018-03-16T11:32:03.341Z',
        sanctionsStatus: 'NOMATCH',
        sanctionsUpdatedAt: '2018-03-16T11:32:03.341Z',
        mediaStatus: 'VALID',
        mediaUpdatedAt: '2018-03-16T11:32:03.341Z',
        politicalExposure: 'VALID',
        politicalExposureUpdatedAt: '2018-03-16T11:32:03.341Z',
      },
    },
  ],
  createdAt: '2019-03-16T12:34:11.341Z',
  contractDocumentEnvelopeStatus: 'CREATED',
  contractDocumentCreatedAt: '2019-03-16T12:34:11.341Z',
  contractDocumentEnvelopeStatusUpdatedAt: '2019-03-16T12:34:11.341Z',
  contract: {
    uri: 'https://google.com',
  },
  productConfigurations: [
    {
      productId: '3552ab85-08da-4bb5-be00-9e94d282d310',
      createdAt: '2019-03-16T12:34:11.341Z',
      product: simpleCheckingProduct,
      initialDeposit: 3000,
    },
  ],
  verificationStatus: {
    faceStatus: 'VALID',
    documentStatus: 'INVALID',
    addressStatus: 'INVALID',
    sanctionsStatus: 'NOMATCH',
    mediaStatus: 'NOMATCH',
    politicalExposure: 'MATCH',
  },
}

export const invalidResponse = {
  statusCode: 400,
  message: 'Request failed with status code 400',
}

export const retryInvalidResponse = {
  statusCode: 401,
  message: 'Request failed with status code 401',
}

export const successCountResponse = {
  count: 2,
}

export const successCountResponseWithPendingFilter = {
  count: 0,
}

export const successCountResponseWithApproveFilter = {
  count: 1,
}
